### ISSUE TITLE
Loader errors

### ISSUE THREAD

**Issue by FloydEdwin** [xingyul/cpnet#6]
hello：
 I have get some errors when i run train_something.sh.I followed the instructions in /utils/data_preparation/README.And last i get the result as your discribed.
/datasets/something-something/gulp_240/
  train/
    Approaching something with your camera/
      xxxxx.gmeta
      xxxxx.gulp
      ...
    Attaching something to something/
      xxxxx.gmeta
      xxxxx.gulp
      ...
    ...
    label2idx.json
    gulp_log.csv
    opts.json
  val/
    Approaching something with your camera/
      xxxxx.gmeta
      xxxxx.gulp
      ...
    Attaching something to something/
      xxxxx.gmeta
      xxxxx.gulp
      ...
    ...
    label2idx.json
    gulp_log.csv
    opts.json
  test/
    0/
      xxxxx.gmeta
      xxxxx.gulp
      ...
    label2idx.json
    gulp_log.csv
    opts.json

However when i run somthing.sh
# a part of something.sh
#!/bin/sh
command_file=`basename "$0"`
script_file=train.py
gpu=0,1,2,3
data=**/home1/Dataset/20bn-something-something-v2/gulp_240**
model=c2d_resnet34_cp_224
model_path=**pretrained_models/ImageNet-ResNet34.npz**
batch_size=32
learning_rate=0.01
num_threads=6
num_frames=12
frame_step=2
width=224
height=224
num_classes=174
decay_step=20
symmetric_flip_labels=86:87,93:94,166:167
log_dir=log_something_something_${model}_${num_frames}_${frame_step}_train
log_file=$log_dir.txt

**I got the errors:**
data loader
**data loading -- 0**
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    batch_size=BATCH_SIZE, num_frames=NUM_FRAMES, step_size=FRAME_STEP, val_samples=1, n_threads=NUM_THREADS)
  File "/home1/user/cpnet/utils/dataloader.py", line 38, in get_loader
    drop_last=True)
  File "/home/user/miniconda3/envs/pytorch_1.0.1_36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "/home/user/miniconda3/envs/pytorch_1.0.1_36/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0

I know what cause the errors is 
self.gd = gulpio.GulpDirectory(data_path) Get the NULLl result . 
Can you help me

**Comment by FloydEdwin** [comment]
Hello I Know what happened ! I used ** pip install gulpio**
 so when **import gulpio** Not the code in cpnet
